apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: spot
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 20
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
    spot: true